#!/usr/bin/env bash

#############
#  ALIASES  #
#############

###
# NAVIGATION
###

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias c="clear"
alias d="cd ~/Downloads"
alias g="git"
alias h="history"
alias l="ls -lAh --group-directories-first --color"
alias p="cd ~/Documents/projects"
alias w="cd ~/Documents/work"


###
# CUSTOM / THIRD PARTY
###

alias fox="/usr/bin/firefox"
alias etcher="balena-etcher-electron"
