- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.local/bin']

- clean:
    ~/:
      force: true
    ~/.local/etc:
      recursive: true

- link:
    # XDG compliance (-)
    ~/.bash: src/bash
    ~/.bashrc: src/bashrc
    ~/.bash_logout: src/bash_logout
    ~/.bash_profile: src/bash_profile
    ~/.ssh/config: src/ssh/config

    # XDG compliance (+)
    ~/.local/etc/cURL/curlrc: src/curlrc
    ~/.local/etc/neofetch/config.conf: src/neofetch.conf
    ~/.local/etc/gem/gemrc: src/gemrc
    ~/.local/etc/git: src/git
    ~/.local/etc/htop/htoprc: src/htoprc
    ~/.local/etc/keepassxc/keepassxc.ini: src/keepassxc.ini
    ~/.local/etc/npm/npmrc: src/npmrc
    ~/.local/etc/pip/pip.conf: src/pip.conf
    ~/.local/etc/gnupg: src/gnupg
    ~/.local/etc/readline/inputrc: src/inputrc
    ~/.local/etc/tmux/tmux.conf: src/tmux.conf
    ~/.local/etc/wget/wgetrc: src/wgetrc

    # Local binary files & scripts
    ~/.local/bin/:
      glob: true
      path: src/bin/*

- shell:
  - [git submodule update --init --recursive, Installing submodules]
