- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '.config', '~/.local/bin']

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ## XDG COMPLIANCE (-)
    ~/.bashrc: src/bashrc
    ~/.bash_logout: src/bash_logout
    ~/.bash_profile: src/bash_profile
    ~/.mozilla/firefox/profiles.ini: src/firefox/profiles.ini
    ~/.mozilla/firefox/two-brain/user.js: src/firefox/user.js
    ~/.ssh/config: src/ssh/config

    ## XDG COMPLIANCE (+)
    ~/.config/bash: src/bash
    ~/.config/cURL/curlrc: src/curlrc
    ~/.config/dir_colors: src/themes/dir_colors
    ~/.config/gem/gemrc: src/gemrc
    ~/.config/git: src/git
    ~/.config/gnupg: src/gnupg
    ~/.config/htop/htoprc: src/htoprc
    ~/.config/keepassxc/keepassxc.ini: src/keepassxc.ini
    ~/.config/kitty/kitty.conf: src/kitty.conf
    ~/.config/neofetch/config.conf: src/neofetch.conf
    ~/.config/npm/npmrc: src/npmrc
    ~/.config/pip/pip.conf: src/pip.conf
    ~/.config/readline/inputrc: src/inputrc
    ~/.config/tmux/tmux.conf: src/tmux.conf
    ~/.config/VSCodium/User/settings.json: src/vscodium.json
    ~/.config/vim/vimrc: src/vimrc
    ~/.config/wget/wgetrc: src/wgetrc
    ~/.config/zathura/zathurarc: src/zathurarc

    # Window manager
    ~/.config/mako/config: src/wm/mako
    ~/.config/rofi/config: src/wm/rofi
    ~/.config/redshift: src/wm/redshift
    ~/.config/sway: src/wm/sway
    ~/.config/swaylock/config: src/wm/swaylock
    ~/.config/waybar: src/wm/waybar

    # Local binary files & scripts
    ~/.local/bin/:
      glob: true
      path: src/bin/*

    # Themes
    ~/.local/share/gedit/styles/nord.xml: src/themes/gedit.xml
    ~/.local/share/rofi/themes/nord.rasi: src/themes/rofi.rasi

    # Backgrounds
    ~/.local/share/backgrounds/:
      glob: true
      path: src/themes/backgrounds/*

- shell:
  - [git submodule update --init --recursive, Installing submodules]
