- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '.config', '~/.local/bin']

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    # XDG compliance (-)
    ~/.bash: src/bash
    ~/.bashrc: src/bashrc
    ~/.bash_logout: src/bash_logout
    ~/.bash_profile: src/bash_profile
    ~/.dir_colors: src/themes/dir_colors
    ~/.mozilla/firefox/profiles.ini: src/firefox/profiles.ini
    ~/.mozilla/firefox/two-brain/user.js: src/firefox/user.js

    ~/.ssh/config: src/ssh/config

    # XDG compliance (+)
    ~/.config/aria2/aria2.conf: src/aria2.conf
    ~/.config/cURL/curlrc: src/curlrc
    ~/.config/neofetch/config.conf: src/neofetch.conf
    ~/.config/gem/gemrc: src/gemrc
    ~/.config/git: src/git
    ~/.config/htop/htoprc: src/htoprc
    ~/.config/keepassxc/keepassxc.ini: src/keepassxc.ini
    ~/.config/kitty/kitty.conf: src/kitty.conf
    ~/.config/npm/npmrc: src/npmrc
    ~/.config/pip/pip.conf: src/pip.conf
    ~/.config/gnupg: src/gnupg
    ~/.config/readline/inputrc: src/inputrc
    ~/.config/tmux/tmux.conf: src/tmux.conf
    ~/.config/VSCodium/User/settings.json: src/vscodium.json
    ~/.config/vim/vimrc: src/vimrc
    ~/.config/wget/wgetrc: src/wgetrc

    # Local binary files & scripts
    ~/.local/bin/:
      glob: true
      path: src/bin/*

    # Themes
    ~/.local/share/gedit/styles/nord.xml: src/themes/gedit.xml

- shell:
  - [git submodule update --init --recursive, Installing submodules]
