#!/bin/bash

##################
#  BASH PROFILE  #
##################

# System wide environment variables and startup programs should go into /etc/profile.
# Personal environment variables and startup programs should go into ~/.bash_profile.
# Personal aliases and functions should go into ~/.bashrc

## ENVIRONMENT VARIABLES ##

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Make vim the default editor
export EDITOR="vim" VISUAL="vim"

## PATH ##
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

if [ -f "$HOME"/.bashrc ]; then
    source ~/.bashrc
fi

# For more information, see https://tiswww.case.edu/php/chet/bash/bashref.html#Bash-Startup-Files
##
