#!/usr/bin/env bash

#################
#  BASH LOGOUT  #
#################

# Clear console on logout for more privacy
if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
