#!/bin/bash

##################
#  BASH PROFILE  #
##################

# System wide environment variables and startup programs should go into /etc/profile.
# Personal environment variables and startup programs should go into ~/.bash_profile.
# Personal aliases and functions should go into ~/.bashrc

if [ -f "$HOME"/.bashrc ]; then
    source ~/.bashrc
fi

# Add `~/.bin` to `$PATH`
if [ -d "$HOME/.bin" ]; then
    export PATH="$HOME/.bin:$PATH";
fi

# For more information, see https://tiswww.case.edu/php/chet/bash/bashref.html#Bash-Startup-Files
##
