#!/usr/bin/env bash

#############
#  BASH RC  #
#############

# System wide environment variables and startup programs should go into /etc/profile.
# Personal environment variables and startup programs should go into ~/.bash_profile.
# Personal aliases and functions should go into ~/.bashrc

# Add `~/.local/lib` to `$PATH`
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH";
fi

# Activate color output for applications that respect the LS_COLORS environment variable
DIRCOLORS=$XDG_CONFIG_HOME/dir_colors

if [ -r "$DIRCOLORS" ]; then
    eval "$(dircolors "$DIRCOLORS")"
fi

unset DIRCOLORS

# For more information,
# see https://www.gnu.org/software/coreutils/manual/html_node/dircolors-invocation.html
##

# Load shell dotfiles
for FILE in "$HOME"/.config/bash/*.bash; do
    [ -r "$FILE" ] && [ -f "$FILE" ] && source "$FILE";
done

unset FILE
