#!/usr/bin/env bash

#############
#  BASH RC  #
#############

# System wide environment variables and startup programs should go into /etc/profile.
# Personal environment variables and startup programs should go into ~/.bash_profile.
# Personal aliases and functions should go into ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


## LSCOLORS ##

# Activate color output for applications that respect the LS_COLORS environment variable
if [ -r "$XDG_CONFIG_HOME/dir_colors" ]; then
    eval "$(dircolors "$XDG_CONFIG_HOME/dir_colors")"
fi

# For more information,
# see https://www.gnu.org/software/coreutils/manual/html_node/dircolors-invocation.html
##


## SHELL CONFIG ##
for FILE in "$HOME"/.config/bash/*.bash; do
    [ -r "$FILE" ] && [ -f "$FILE" ] && source "$FILE";
done

unset FILE

# For more information,
# see https://tiswww.case.edu/php/chet/bash/bashref.html#Bash-Startup-Files
##


## PROMPT ##

# Load starship prompt
eval "$(starship init bash)"

# For more information,
# see https://github.com/starship/starship
##
