#!/bin/bash

#############
#  ALIASES  #
#############

###
# NAVIGATION
###

# many dots, so levels, wow
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Listing files
alias l='ls -CF'
alias ll='ls -alF'
alias la='ls -A'

# Replace previous aliases in case `exa` is installed
# See https://the.exa.website
if command -v exa >/dev/null 2>&1; then
    alias l="exa --git --color=automatic"
    alias ls="exa --git --color=automatic"
    alias ll="exa --all --long --git --color=automatic"
    alias la="exa --all --binary --group --header --long --git --color=automatic"
fi

# Shortcuts
alias b="firefox"
alias c="clear"
alias d="cd ~/Downloads"
alias g="git"
alias h="history"
alias p="cd ~/Documents/projects"
alias w="cd ~/Documents/work"


###
# BASICS
###

# Allow aliases to be with sudo
alias sudo="sudo "

# Copy & Paste file contents from the command-line
alias cpy='xclip -selection clipboard'
alias pst='xclip -selection clipboard -o'

# Copy public key to clipboard:
alias pubkey="cpy ~/.ssh/id_rsa.pub | echo '=> Public key copied to pasteboard.'"

# Show file statistics for current directory
alias du="du -sh ./* | sort -hr"

# Human-readable disk usage
alias df="df -Tha --total"

# Show processes
alias psa="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"


###
# MISCELLANEOUS
###

# Lock the screen (when going AFK) - For locking the screen, use 'SUPER+L'
alias afk="sudo systemctl suspend"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Thinking of http://xkcd.com/530/ - Linux version @mathiasbynensalias
alias stfu="amixer -q sset Master 0%"
alias pumpitup="amixer -q sset Master 100%"

# List ten most popular commands
alias popular="history | awk '{CMD[\$2]++;count++;}END { for (a in CMD)print CMD[a] \" \" CMD[a]/count*100 \"% \" a;}' | grep -v \"./\" | column -c3 -s \" \" -t | sort -nr | nl |  head -n10"


###
# SOFTWARE
###

alias bi="buildah images"
alias bc="buildah containers"
alias etcher="balena-etcher-electron"


###
# HARDWARE
###

alias motherboard="dmidecode -t 2 | less"
alias cpu="dmidecode -t 4 | less"
alias memory="dmidecode -t 17 | less"
