#!/bin/bash

#################
#  BASH PROMPT  #
#################

# Get current git branch
get_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/'
}

# Build PS1
PS1="[\A] \u@\h:\w\$(get_branch)\n\\$ "
export PS1;
